### PR TITLE
Improve entities selection

### PR DESCRIPTION
**Pull request by brenard**
To make easier the selection of entities in preferences, I made some changes to display their name in addition of their ID. I also sorted entities by name and add a search input to easily filter entries inside long list.

The entities label could now be quite long, so I propose to display the checkbox first to make it always visible. For the same reason, I switched to a horizontal menu for tabs.

I also removed the dead code about experimental group switchs.

Note: I started with a code cleaning commit to remove trailing spaces inside JS files to make my feature commit cleaner.

### CODE REVIEW

**Comment by geoph9** [comment]
Hi @brenard,

Your PR seems useful although I am having trouble running your code successfully. In particular, I am getting the following error: `TypeError: searchEntry.set_search_delay is not a function` .

Could you share your environment details?

**Comment by brenard** [comment]
Oh OK, you probably use an OS with gtk3. I'm using Debian 12 with Gnome 44 and gtk4. The activation delay of the search-changed event can be adjusted since gtk4 and it's hard-coded to [150ms in Gtk3](https://docs.gtk.org/gtk3/signal.SearchEntry.search-changed.html#description). A can't found a default value with [gtk4](https://docs.gtk.org/gtk4/signal.SearchEntry.search-changed.html#description) and I mean it's zero (due to my tests without it). So, we probably could fix it by adding a condition on if the method exist. I will do it and update PR.

**Comment by geoph9** [comment]
Oh that's good to know. Yes, I actually tested this from my work computer and forgot that I am not using gtk4. That if-method-exists check sounds like the way to go!

**Comment by geoph9** [comment]
I just tested this on Gnome 44 and everything works fine. Thanks!

**Pull request merged**
