### PR TITLE
Make extension asynchronous and more

### PR DESCRIPTION
**Pull request by brenard**
As discuss in #61, I have worked on making the extension more asynchronous, especially during loading entities. I globally rework on how the extension is initialized, how events are handled and how HASS entities are requested to make it asynchronous and using callback.

I also :

- add a refresh button in preferences menu (translation update need, french already done).
- clean code to avoid duplicating configuration key constants
- remove _Long-Live-Access-Tokens_ entry from schema & settings since it was stored using `gi.Secret`
- make debugging easier by prefixing all logged message with the extension UUID (use `journalctl -o cat -g hass-gshell -f` the follow logs)

### CODE REVIEW

**Comment by geoph9** [comment]
Thank you @brenard! This seems great and you made some much needed changes. 

Since this is a relatively big PR (for the size of the app), I'll have to test it a bit more extensively, but I'll try to finish the review by the weekend. Some initial comments:
- In `computeURL`, `if (!url.startsWith("http"))` should be `if (!url.startsWith("http://"))` if I am not mistaken.
- Have you tested the "refresh every X seconds" functionality? I am referring to the `_refreshPanelSensors` function in `extension.js`. I don't think it currently works considering the function returns only false or null.
- (minor) Use of both `@param {function}` and `@param {Function}` in docstrings (I'd go with capital `Function`).

Thanks again for the great work!

**Comment by brenard** [comment]
> Thank you @brenard! This seems great and you made some much needed changes.
> 
> Since this is a relatively big PR (for the size of the app), I'll have to test it a bit more extensively, but I'll try to finish the review by the weekend. 

It seem totally normal  :smile: 

> Some initial comments:
> 
>     * In `computeURL`, `if (!url.startsWith("http"))` should be `if (!url.startsWith("http://"))` if I am not mistaken.
You'r right. I just taken what is initially done in [`extension.js`](https://github.com/geoph9/hass-gshell-extension/blob/6c31b24e94ed174456ed5582d50fe04abb3284ea/extension.js#L202), but we could do better. I propose [this solution using regexp](https://github.com/geoph9/hass-gshell-extension/pull/62/commits/bed7d0ef6b83e534674d80654f99f8c6dcad841b).

>     * Have you tested the "refresh every X seconds" functionality? I am referring to the `_refreshPanelSensors` function in `extension.js`. I don't think it currently works considering the function returns only false or null.
You'r right ! I fix [that](https://github.com/geoph9/hass-gshell-extension/pull/62/commits/0f709734b889e4f37ff4c72556da4397ff96690b) and also a [historical bug](https://github.com/geoph9/hass-gshell-extension/pull/62/commits/284bcafacce265356e435ff6d0bd53e12a0d7301) on setting refresh rate.

>     * (minor) Use of both `@param {function}` and `@param {Function}` in docstrings (I'd go with capital `Function`).
Of course, it [fixed](https://github.com/geoph9/hass-gshell-extension/pull/62/commits/c15583c9dbbdc2cabe4106381f4f3c876a5140a0).

**Comment by brenard** [comment]
__Note:__ It's not relative with _async_ feature, but since translations have to be reworked, may be we could modify the _"Add"_ buttons label in preferences. I think that label should be something like _"Save"_ or _"Apply"_ instead.

**Comment by geoph9** [comment]
I admire your efficiency! 
- Using regex for the http pattern is better, I agree.
- Using _"Apply"_ instead of _"Add"_ sounds like a good idea, let's go for it.

**Comment by brenard** [comment]
> I admire your efficiency!

I start knowing well the subject :smile: 

>     * Using regex for the http pattern is better, I agree.
Nice !

>     * Using _"Apply"_ instead of _"Add"_ sounds like a good idea, let's go for it.
[Done](https://github.com/geoph9/hass-gshell-extension/pull/62/commits/d14a39cc85e321848a49642867d5c5b63ac08750)

On the other side, I detect an issue when locking screen: the panel indicator disappear :face_with_spiral_eyes: It seem due to the fact that the extension is disabled on locking and re-enabled after we connect back. Inside the `disable()` method, we are doing a `this.destroy()` and on re-enabling, the `Main.panel.addToStatusArea()` failed because the object is already destroyed.

I made a [quick fix](https://github.com/geoph9/hass-gshell-extension/pull/62/commits/29aeb3ba7b92e7c7376ab8e77ba653294afa4074) by managing enabling/disabling extension outside of the _PanelButton_ object and I think (but I'm not sure) the right way is to create another class for the extension (as explain in the [gjs guide](https://gjs.guide/extensions/development/creating.html#extension-js)) to hold the major part of the extension features and leave in the _HassMenu_ class just what is about the indicator and its menu.

**Comment by brenard** [comment]
I finally globally rework on the structure of the `extension.js` file to fix problem when enabling/disabling the extension (manually or automatically when screen is locked). I'm sorry because this PR is now quite not only about asynchronous feature, I change a lot of things, even if the my first goal is to stabilize the existing features.

I will try to quickly explain what I have done and why :

- All the extension's component are now regrouped inside one `St.BoxLayout()` element
- Building and refreshing tasks of the components are now separated inside different building and refreshing methods. This allow to firstly build the components and put them inside the main Box in a defined order. Furthermore, refreshing tasks now only refresh non-static elements.
- The tray icon is now inside a button which is inside the main box. The event to open the menu is connected on this button and click event is disabled on the `PopupMenu` to leave click events to be handled by components inside the main box.
- Settings are now loaded inside the `_loadSettings()` method and their changes are now individually and directly connected to the right refreshing method.
- All components are now stored inside properties of the main `PopupMenu` object, which are initialized to null by the `_init()` method. That allow to properly destroy each of them when disabling the extension and avoid problems. This is managed by the `disable()` method of the `PopupMenu` object which call some other methods for each parts of the extension.
- An `Extension` class have been created to manage the enabling/disabling of the extension, outside the `PopupMenu` component to avoid problems when enabling/disabling the extension. In future, we could move more stuff from the `HassMenu` to the `Extension` class and only leave inside the `HassMenu` stuff related to the popup menu content. Furthermore, all sensors could be managed with an individual `St.Bin` derived object that could be stacked inside the main Box. It could greatly facilitate the possibility of loading and refreshing the state of the sensors individually.

I also made some improvements now easily achievable:

- the change on selected tray icon is now directly effective (no Gnome shell restart need). Note: I remove the note about that on the preferences windows.
- I removed _"(Currently Broken)"_ note about Temperature/Humidity Sensors refreshing feature.
- I consequently update the `hass-gshell.pot` and the french translation
- I add icons to the togglable menu items base on the entity type (trivial mapping). I add for that 3 new SVG image files from the MDI collection (same used in HASS).
- finally, I also add an icon on the HASS events sub-menu. _Note:_ the icon is not aligned as others icons in the popup menu and it seem "normal" (I use the way intended for adding an icon to a `PopupSubMenuMenuItem`). May be we could force a different alignment, but I don't know how we could do that.

I hope all these changes as been done I a proper way for you.

**Comment by brenard** [comment]
Last thing for today: with my last changes, I added a lot of useful debugging messages for developers, but not for _regular_ user. Furthermore, I saw that the [review guidelines](https://gjs.guide/extensions/review-guidelines/review-guidelines.html#no-excessive-logging) don't want too excessive logging. Consequently, I added a debug mode option and a `_log()` method in the `utils.js` file to easily log messages and handle this mode. This method also handle message formatting for better code readability.

**Comment by geoph9** [comment]
Hello again, thanks for this great PR! I learned a lot just by reviewing your code.

I set up a mock hass server with flask to test your modifications (I haven't used home-assistant in a while and my current server is buggy). Most things seem to be working fine!

Regarding the UI, this update makes the new icon look smaller than other extensions. In addition, the fact that the icon and temperature components belong to the same layout, makes hovering a bit "ugly" (see screenshot below). This is not a huge issue for me, but do you know if the central's `BoxLayout`'s hovering effect can be disabled? Plus, what could we do to make the icon keep it's original size? Is it possible to set the `BoxLayout`'s margin (top and bottom) to 0 so that the icon will be able to expand?
image


Since the `Panel Sensors` tab adds the sensor stats automatically, then I'd say it is also safe to remove the `Show Temperature/Humidity` and `Show Humidity` options  from the main prefs menu. Plus the `Temperature ID` and `Humidity ID` entries are also redundant.

I'll take a closer look at the code in the upcoming days and let you know of any comments. Thanks again for the great work!

**Review by geoph9 — CHANGES_REQUESTED** [review]
I made some basic functionality tests (on top of the ones mentioned above) and I think that everything is good to go. Before merging, the following need to be addressed:
- Remove hovering effect from the main box layout. 
- Minimize margins of the top-level box layout so that the icon will have the same dimensions as the rest of the tray icons.
- Increase the extension's version in metadata.json, to version 16 (I don't really like that versioning scheme, but let's keep it that way for now).
- Change the "shell-version" entry in metadata.json to only accept "44". I have personally not tested it on Gnome 43 and I am not very optimistic it would work out of the box.
- In the `disable` function of `Extension`, change `Utils._logs` to `Utils._log` since it currently leads to a bug.

**Comment by geoph9** [comment]
On top of the above, I just discovered a bug where when I press refresh the list of togglable entities are appended instead of deleted and re-added. See below:
image

**Comment by brenard** [comment]
> I made some basic functionality tests (on top of the ones mentioned above) and I think that everything is good to go. Before merging, the following need to be addressed:
> 
>     * (**Important**) In the `disable` function of `Extension`, change `Utils._logs` to `Utils._log` since it currently leads to a bug.

[Fixed](https://github.com/geoph9/hass-gshell-extension/pull/62/commits/f081121a62127f95f590a2c197eb93742d851193)

>     * (**Important**) Humidity/Temperature Stats are showing even when the `Show Temperature/Humidity` option is off in the settings. There should be an extra check in `extension.js` when deciding to add these stats on the tray.

I can't reproduce this bug on my installations. Furthermore, I totally agree on the fact we could remove this Temperature/Humidity dedicated feature and only keep the sensors panel. May be I could do it if it's OK for you?

>     * (**Important**) Increase the extension's version in metadata.json, to version 16 (I don't really like that versioning scheme, but let's keep it that way for now).

[Done](https://github.com/geoph9/hass-gshell-extension/pull/62/commits/252bfda7b5a76edee261c4eec60a7a917586d67c)

>     * (**Important**) Change the "shell-version" entry in metadata.json to only accept "44". I have personally not tested it on Gnome 43 and I am not very optimistic it would work out of the box.

In fact, on my second laptop, I'm using Gnome 43.4 and it seem work as on my Gnome 44.

>     * (**Desired**) Remove hovering effect from the main box layout.

I finally [find the solution](https://github.com/geoph9/hass-gshell-extension/pull/62/commits/4f9237d89622213cfe8625f568af65732cc20ad2) for that (thank to the _LookingGlass_ tool).

>     * (**Desired**) Minimize margins of the top-level box layout so that the icon will have the same dimensions as the rest of the tray icons.

It hope it come with the same style class removed for the previous problem. In fact, it seem due to your Gnome theme. On my Debian installations (with the default theme), I had no margin.

>     * (**Optional**) For some reason, when changing a submenu in the settings, it automatically scrolls down to the middle of the page. E.g. when pressing `Togglables` it scrolls down and hides the horizontal menu. This is a bit annoying. Do you think it would be easy to have the pages fixed to the top?

Yes, I already saw this problem, but I can't find a way to fix it. After some research on this subject, I started to bootstrap a new preferences windows based on [Adw lib](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/widget-gallery.html). It seem a good way to fix that and upgrade it to use the latest Gnome style preferences window.

> On top of the above, I just discovered a bug where when I press refresh the list of togglable entities are appended instead of deleted and re-added.

Yes, I discovered this problem on my second laptop even if I can't reproduce the problem on my main one. I [fixed](https://github.com/geoph9/hass-gshell-extension/pull/62/commits/4e80fb24b3606112e87d56b18598cb4e5dfe09df) it.

**Comment by brenard** [comment]
I implemented a new preferences windows based on [Adw lib](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/widget-gallery.html). As proposed, I removed all stuff about temperature & humidity sensors and move refreshing feature on sensors panel.

I also implemented the _show notifications_ option present in the schema.

**Comment by geoph9** [comment]
Thank you for this great update! I have noticed the following issues with the new prefs window:
- When starting from scratch (i.e. the hass-url and hass-access-token are not set), the `General Settings`, `Togglables` and `Sensors` pane does not appear. 
  - This means that when the user enters their url and access-token, they need to close the Settings window and re-open it so that the panes will appear.
  - Could you make it so that the panes are already there (empty at first) and when a url and valid access-token are inserted, they are automatically refreshed  (without having to close and re-open the window)?
  - (Note) You can test this by changing the url -> re-opening the window -> re-entering the correct url. You will notice that you will have to close and re-open the window in order to see the togglables and sensors.
- There is no `Save` (or `Apply`) button to submit the url and access token entries. Some users might be confused by that.
- For some reason, whenever I toggle an option, I get a warning (see screenshot) even though the toggling was successful (of course this doesn't happen when `Show notifications` is false).
image
- Wouldn't it be better if `Show notifications` defaulted to false?

P.S. I love the new preferences window! I'll definitely use AdW in the future.

**Comment by brenard** [comment]
> Thank you for this great update! I have noticed the following issues with the new prefs window:
> 
>     * When starting from scratch (i.e. the hass-url and hass-access-token are not set), the `General Settings`, `Togglables` and `Sensors` pane does not appear.
>       
>       * This means that when the user enters their url and access-token, they need to close the Settings window and re-open it so that the panes will appear.
>       * Could you make it so that the panes are already there (empty at first) and when a url and valid access-token are inserted, they are automatically refreshed  (without having to close and re-open the window)?
>       * (Note) You can test this by changing the url -> re-opening the window -> re-entering the correct url. You will notice that you will have to close and re-open the window in order to see the togglables and sensors.
> 
>     * There is no `Save` (or `Apply`) button to submit the url and access token entries. Some users might be confused by that.

Yes, it's [done](https://github.com/geoph9/hass-gshell-extension/pull/62/commits/5bd03d65e7cc8ccb7152ec29ca1caf34001cc27e).

>     * For some reason, whenever I toggle an option, I get a warning (see screenshot) even though the toggling was successful (of course this doesn't happen when `Show notifications` is false).
>       image

Yes, I also observed this bug this morning. It seem due to the fact that HA do not always put in this response the state of the toogled entity. Furthermore, I noticed (in [doc](https://developers.home-assistant.io/docs/api/rest/) that it could send the state of multiple entities and not only the one we requested. So, I adjusted [how I handle the HA response](https://github.com/geoph9/hass-gshell-extension/pull/62/commits/487654d27d69d69cb69f1167f44bc114373df7b7).

>     * Wouldn't it be better if `Show notifications` defaulted to false?

No problem, [done](https://github.com/geoph9/hass-gshell-extension/pull/62/commits/ee3d68208f5282342585f15d0475ee784c4f9a48).

__Note:__ I also observed that when I open my session, the HA token could not be retrieved during some time and after a will, it will be returned. I don't understand why and I only noticed that on one of my laptop (with Gnome 44). Consequently, I [adjusted](https://github.com/geoph9/hass-gshell-extension/pull/62/commits/081ba080cf852b3781872b14d111db2113f63081) the `_constructMessage()` function to properly handle this case.

**Comment by brenard** [comment]
I finally manage to split panel sensors in dedicated `St.Bin` objects and handle them individually. This permit to:

* do not load all entities from HA on startup, but only enabled ones
* refresh them individually when clicking on it by requesting only one entity to HA API

I would love to add a tooltip on them the display corresponding entity name, but I haven't figured out how to do it yet.

Furthermore, I also fix handling disconnecting settings when disabling extension to avoid error after screen locked/unlocked.

**Comment by geoph9** [comment]
Everything looks great! For some reason I am having trouble refreshing sensors by clicking on them on the pane. When doing so, I get the placeholder text, implying that the entity returned is in the wrong formatl (no notification or error is shown).  I'll test this again on my other laptop and debug it more thoroughly.

Besides that, is it easy to add a `Submit` or `Apply` button on the `URL` and `Access Token` entries of the preferences?

Regarding the tooltip text, I think I also tried to do this at some point and didn't manage to find a solution 😅 .

**Comment by brenard** [comment]
> Everything looks great! For some reason I am having trouble refreshing sensors by clicking on them on the pane. When doing so, I get the placeholder text, implying that the entity returned is in the wrong formatl (no notification or error is shown). I'll test this again on my other laptop and debug it more thoroughly.

I do not implemented error notification in this case, because I think it could quite annoying if in some circonstance, we can't access to your HA instance. If you have the placeholder, it's mean the refreshing request is correctly handled but we fail to retrieve the current state of the entity from the HA API. I [improved requests debugging](https://github.com/geoph9/hass-gshell-extension/pull/62/commits/62bd5846cd3bed8a6b5041b3fb584cad4c73bdfe): could you please test again and send me the log output ? Just in case, you can use the `journalctl -f -g hass-gshell@geoph9-on-github` command to see log and be sure to enable the debug mode in preferences.

> Besides that, is it easy to add a `Submit` or `Apply` button on the `URL` and `Access Token` entries of the preferences?

Ok, yes, I completely forget your request about that. Moreover, `Adw.EntryRow` [have a `show_apply_button` for that](https://github.com/geoph9/hass-gshell-extension/pull/62/commits/d08fde06fa74d82390574959bca526ed0ef09229) :smile: ! I love this lib :heart_decoration: !

> Regarding the tooltip text, I think I also tried to do this at some point and didn't manage to find a solution sweat_smile .

May be we will finally found the solution ! I threw a bottle overboard for that :pray: 

https://discourse.gnome.org/t/tooltip-on-a-st-bin-in-an-extension-indicator-in-status-bar/16105

**Comment by brenard** [comment]
> May be we will finally found the solution ! I threw a bottle overboard for that pray
> 
> https://discourse.gnome.org/t/tooltip-on-a-st-bin-in-an-extension-indicator-in-status-bar/16105

Thanks to andyholme, we finally have tooltip ! :smile:

**Comment by geoph9** [comment]
That's great! Wouldn't it be better if we only showed the friendly name on the tooltip? Currently the text seems too big.

I am not sure why, but the apply button still doesn't appear in my prefs. Any idea why?

image

Everything else seems great, and I think we are about to merge this!

**Comment by brenard** [comment]
> That's great! Wouldn't it be better if we only showed the friendly name on the tooltip? Currently the text seems too big.

You're right, [done](https://github.com/geoph9/hass-gshell-extension/pull/62/commits/db0e1c27a940f25ff44839ac18dc28c484180945).

> I am not sure why, but the apply button still doesn't appear in my prefs. Any idea why?

You have to start editing and change the field value to see the apply button.
Screencast

**Comment by geoph9** [comment]
Everything looks great, I can't find anything wrong on the surface and all of my tests pass. I am going to merge this into master now, and I'll upload a release on e.g.o. within the next couple of days.

Thanks for the great work @brenard !

**Pull request merged**
